### ISSUE TITLE
How to export command errors in ams ErrorSerializer?

### ISSUE THREAD

**Issue by smartepsh** [nebulab/simple_command#4]
[JSON API Errors Document in AMS](https://github.com/rails-api/active_model_serializers/blob/master/docs/jsonapi/errors.md)
I want to render the error message by using AMS jsonapi serializer.
But there is something wrong if I render a simple_command result.
I can render the errors to json but can not to jsonapi.

``` ruby
#simple_command
Class AuthenticateUser
*
*
  errors.add :user_authentication, 'invalid credentials'
*
*
end
#controller
command = AuthenticateUser.call(params[:email], params[:password])

render json: command, status: 401, adapter: :json_api, serializer: ActiveModel::Serializer::ErrorSerializer
```

log:

``` log
NoMethodError (undefined method `messages' for {:user_authentication=>["invalid credentials"]}:SimpleCommand::Errors):

app/controllers/authentication_controller.rb:10:in `authenticate'
```

What should I do?

**Comment by kennyadsl** [comment]
Hey there,

from the page you linked:

> The resource MUST have a non-empty associated #errors object. The errors object must have a #messages method that returns a hash of error name to array of descriptions.

which `SimpleCommand::Errors` doesn't currently have. 

If you want to add this method, feel free to submit a PR with this change.

**Comment by smartepsh** [comment]
thanks...I'll try..

**Comment by kennyadsl** [comment]
Going to close this one, feel free to open another issue or submit that PR. Thanks!

**Comment by denniscastro** [comment]
Hi 
I have the same problem

Just add:

```
    module SimpleCommand
        class Errors
            def messages
               self
            end
        end
    end
```
